sudo: required
language: node_js
before_script:
    - npm install -g gulp
    - npm install -g istanbul
    - npm isntall -g mocha
after_success:
    - bash <(curl -s https://codecov.io/bash)
script: 
    - gulp test
    - istanbul cover node_modules/mocha/bin/_mocha
node_js:
    - "6"
    - "6.1"
    - "5.11"